name: rest_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  jwt_decoder: ^2.0.1
  mongo_dart: ^0.10.3

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
